{{- $fullname := include "devops-doris-test.fullname" . -}}
{{- $labels := include "devops-doris-test.labels" .  }}
{{- $Files := .Files -}}

{{- range $secret := .Values.secrets}}
{{- if $secret.create }}
apiVersion: v1
kind: Secret
metadata: 
  name: "{{ $fullname }}-{{ $secret.name }}"
  labels:
{{ $labels | indent 4 }}
type: Opaque
data:
  {{- $path := printf "config/secrets/%s" $secret.file }}
  {{- ($Files.Glob $path).AsSecrets | nindent 2 }}




---
{{- end }}
{{- end }}